### ISSUE TITLE
CheckoutCest doesn't work for Magento 1.9.1.1

### ISSUE THREAD

**Issue by ceckoslab** [Zifius/Magento-Codeception#2]
I tired to run the tests from CheckoutCest.php, but the tests have filed, because Magento 1.9.1.1 has different html structure of the older Magento versions.

We can try 2 solutions:
- As @Zifius suggested we can use Page Objects - http://codeception.com/docs/07-AdvancedUsage#PageObjects to store different css selectors for the different Magento versions 
- We can analize different Magento versions and to find the best css selectors that work for all Magento versions

**Comment by Zifius** [comment]
@ceckoslab should be fixed now
